import type { BookSet, MathDomain } from "../../types/knowledge.ts";

export interface LessonMetadata {
  volume: 1 | 2;
  chapter: number;
  chapterTitle: string;
  lesson: number;
  lessonTitle: string;
  topicId: string;
  domain: MathDomain;
  startPage: number;
  endPage: number;
}

export const TOAN8_KNTT_CURRICULUM: LessonMetadata[] = [
  // --- TẬP 1 (Chương 1, 2, 3, 4, 5) ---
  {
    volume: 1,
    chapter: 1,
    chapterTitle: "Đa thức",
    lesson: 1,
    lessonTitle: "Đơn thức",
    topicId: "don-thuc-da-thuc",
    domain: "ALGEBRA",
    startPage: 5,
    endPage: 9,
  },
  {
    volume: 1,
    chapter: 1,
    chapterTitle: "Đa thức",
    lesson: 2,
    lessonTitle: "Đa thức",
    topicId: "don-thuc-da-thuc",
    domain: "ALGEBRA",
    startPage: 10,
    endPage: 14,
  },
  {
    volume: 1,
    chapter: 1,
    chapterTitle: "Đa thức",
    lesson: 3,
    lessonTitle: "Phép cộng và phép trừ đa thức",
    topicId: "don-thuc-da-thuc",
    domain: "ALGEBRA",
    startPage: 15,
    endPage: 19,
  },
  {
    volume: 1,
    chapter: 1,
    chapterTitle: "Đa thức",
    lesson: 4,
    lessonTitle: "Phép nhân đa thức",
    topicId: "don-thuc-da-thuc",
    domain: "ALGEBRA",
    startPage: 20,
    endPage: 23,
  },
  {
    volume: 1,
    chapter: 1,
    chapterTitle: "Đa thức",
    lesson: 5,
    lessonTitle: "Phép chia đa thức cho đơn thức",
    topicId: "don-thuc-da-thuc",
    domain: "ALGEBRA",
    startPage: 24,
    endPage: 28,
  },
  {
    volume: 1,
    chapter: 2,
    chapterTitle: "Hằng đẳng thức đáng nhớ và ứng dụng",
    lesson: 6,
    lessonTitle: "Hiệu hai bình phương. Bình phương của một tổng hay một hiệu",
    topicId: "hang-dang-thuc",
    domain: "ALGEBRA",
    startPage: 29,
    endPage: 34,
  },
  {
    volume: 1,
    chapter: 2,
    chapterTitle: "Hằng đẳng thức đáng nhớ và ứng dụng",
    lesson: 7,
    lessonTitle: "Lập phương của một tổng. Lập phương của một hiệu",
    topicId: "hang-dang-thuc",
    domain: "ALGEBRA",
    startPage: 35,
    endPage: 39,
  },
  {
    volume: 1,
    chapter: 2,
    chapterTitle: "Hằng đẳng thức đáng nhớ và ứng dụng",
    lesson: 8,
    lessonTitle: "Tổng và hiệu hai lập phương",
    topicId: "hang-dang-thuc",
    domain: "ALGEBRA",
    startPage: 40,
    endPage: 43,
  },
  {
    volume: 1,
    chapter: 2,
    chapterTitle: "Hằng đẳng thức đáng nhớ và ứng dụng",
    lesson: 9,
    lessonTitle: "Phân tích đa thức thành nhân tử",
    topicId: "phan-tich-da-thuc-thanh-nhan-tu",
    domain: "ALGEBRA",
    startPage: 44,
    endPage: 50,
  },
  {
    volume: 1,
    chapter: 3,
    chapterTitle: "Tứ giác",
    lesson: 10,
    lessonTitle: "Tứ giác",
    topicId: "tu-giac",
    domain: "GEOMETRY",
    startPage: 51,
    endPage: 54,
  },
  {
    volume: 1,
    chapter: 3,
    chapterTitle: "Tứ giác",
    lesson: 11,
    lessonTitle: "Hình thang cân",
    topicId: "hinh-thang-can",
    domain: "GEOMETRY",
    startPage: 55,
    endPage: 59,
  },
  {
    volume: 1,
    chapter: 3,
    chapterTitle: "Tứ giác",
    lesson: 12,
    lessonTitle: "Hình bình hành",
    topicId: "hinh-binh-hanh-chu-nhat-thoi-vuong",
    domain: "GEOMETRY",
    startPage: 60,
    endPage: 64,
  },
  {
    volume: 1,
    chapter: 3,
    chapterTitle: "Tứ giác",
    lesson: 13,
    lessonTitle: "Hình chữ nhật",
    topicId: "hinh-binh-hanh-chu-nhat-thoi-vuong",
    domain: "GEOMETRY",
    startPage: 65,
    endPage: 69,
  },
  {
    volume: 1,
    chapter: 3,
    chapterTitle: "Tứ giác",
    lesson: 14,
    lessonTitle: "Hình thoi và hình vuông",
    topicId: "hinh-binh-hanh-chu-nhat-thoi-vuong",
    domain: "GEOMETRY",
    startPage: 70,
    endPage: 78,
  },
  {
    volume: 1,
    chapter: 4,
    chapterTitle: "Định lý Thalès",
    lesson: 15,
    lessonTitle: "Định lý Thalès trong tam giác",
    topicId: "dinh-ly-thales",
    domain: "GEOMETRY",
    startPage: 79,
    endPage: 85,
  },
  {
    volume: 1,
    chapter: 4,
    chapterTitle: "Định lý Thalès",
    lesson: 16,
    lessonTitle: "Đường trung bình của tam giác",
    topicId: "dinh-ly-thales",
    domain: "GEOMETRY",
    startPage: 86,
    endPage: 90,
  },
  {
    volume: 1,
    chapter: 4,
    chapterTitle: "Định lý Thalès",
    lesson: 17,
    lessonTitle: "Tính chất đường phân giác của tam giác",
    topicId: "dinh-ly-thales",
    domain: "GEOMETRY",
    startPage: 91,
    endPage: 98,
  },
  {
    volume: 1,
    chapter: 5,
    chapterTitle: "Dữ liệu và biểu đồ",
    lesson: 18,
    lessonTitle: "Thu thập và phân loại dữ liệu",
    topicId: "thong-ke-va-xac-suat",
    domain: "STATISTICS_PROBABILITY",
    startPage: 99,
    endPage: 106,
  },
  {
    volume: 1,
    chapter: 5,
    chapterTitle: "Dữ liệu và biểu đồ",
    lesson: 19,
    lessonTitle: "Biểu diễn dữ liệu bằng bảng, biểu đồ",
    topicId: "thong-ke-va-xac-suat",
    domain: "STATISTICS_PROBABILITY",
    startPage: 107,
    endPage: 126,
  },

  // --- TẬP 2 (Chương 6, 7, 8, 9, 10) ---
  {
    volume: 2,
    chapter: 6,
    chapterTitle: "Phân thức đại số",
    lesson: 21,
    lessonTitle: "Phân thức đại số",
    topicId: "phan-thuc-dai-so",
    domain: "ALGEBRA",
    startPage: 5,
    endPage: 11,
  },
  {
    volume: 2,
    chapter: 6,
    chapterTitle: "Phân thức đại số",
    lesson: 22,
    lessonTitle: "Tính chất cơ bản của phân thức đại số",
    topicId: "phan-thuc-dai-so",
    domain: "ALGEBRA",
    startPage: 12,
    endPage: 18,
  },
  {
    volume: 2,
    chapter: 6,
    chapterTitle: "Phân thức đại số",
    lesson: 23,
    lessonTitle: "Phép cộng và phép trừ phân thức đại số",
    topicId: "phan-thuc-dai-so",
    domain: "ALGEBRA",
    startPage: 19,
    endPage: 25,
  },
  {
    volume: 2,
    chapter: 6,
    chapterTitle: "Phân thức đại số",
    lesson: 24,
    lessonTitle: "Phép nhân và phép chia phân thức đại số",
    topicId: "phan-thuc-dai-so",
    domain: "ALGEBRA",
    startPage: 26,
    endPage: 34,
  },
  {
    volume: 2,
    chapter: 7,
    chapterTitle: "Phương trình bậc nhất và hàm số bậc nhất",
    lesson: 25,
    lessonTitle: "Phương trình bậc nhất một ẩn",
    topicId: "phuong-trinh-bac-nhat",
    domain: "ALGEBRA",
    startPage: 35,
    endPage: 42,
  },
  {
    volume: 2,
    chapter: 7,
    chapterTitle: "Phương trình bậc nhất và hàm số bậc nhất",
    lesson: 26,
    lessonTitle: "Giải bài toán bằng cách lập phương trình",
    topicId: "phuong-trinh-bac-nhat",
    domain: "ALGEBRA",
    startPage: 43,
    endPage: 49,
  },
  {
    volume: 2,
    chapter: 7,
    chapterTitle: "Phương trình bậc nhất và hàm số bậc nhất",
    lesson: 27,
    lessonTitle: "Khái niệm hàm số và đồ thị của hàm số",
    topicId: "ham-so-bac-nhat",
    domain: "ALGEBRA",
    startPage: 50,
    endPage: 56,
  },
  {
    volume: 2,
    chapter: 7,
    chapterTitle: "Phương trình bậc nhất và hàm số bậc nhất",
    lesson: 28,
    lessonTitle: "Hàm số bậc nhất y = ax + b",
    topicId: "ham-so-bac-nhat",
    domain: "ALGEBRA",
    startPage: 57,
    endPage: 64,
  },
  {
    volume: 2,
    chapter: 7,
    chapterTitle: "Phương trình bậc nhất và hàm số bậc nhất",
    lesson: 29,
    lessonTitle: "Hệ số góc của đường thẳng",
    topicId: "ham-so-bac-nhat",
    domain: "ALGEBRA",
    startPage: 65,
    endPage: 73,
  },
  {
    volume: 2,
    chapter: 8,
    chapterTitle: "Mở đầu về tính xác suất của biến cố",
    lesson: 30,
    lessonTitle: "Kết quả có thể và kết quả thuận lợi",
    topicId: "thong-ke-va-xac-suat",
    domain: "STATISTICS_PROBABILITY",
    startPage: 74,
    endPage: 80,
  },
  {
    volume: 2,
    chapter: 8,
    chapterTitle: "Mở đầu về tính xác suất của biến cố",
    lesson: 31,
    lessonTitle: "Cách tính xác suất của biến cố bằng tỉ số",
    topicId: "thong-ke-va-xac-suat",
    domain: "STATISTICS_PROBABILITY",
    startPage: 81,
    endPage: 87,
  },
  {
    volume: 2,
    chapter: 8,
    chapterTitle: "Mở đầu về tính xác suất của biến cố",
    lesson: 32,
    lessonTitle: "Mối liên hệ giữa xác suất thực nghiệm và xác suất lý thuyết",
    topicId: "thong-ke-va-xac-suat",
    domain: "STATISTICS_PROBABILITY",
    startPage: 88,
    endPage: 96,
  },
  {
    volume: 2,
    chapter: 9,
    chapterTitle: "Tam giác đồng dạng",
    lesson: 33,
    lessonTitle: "Hai tam giác đồng dạng",
    topicId: "tam-giac-dong-dang",
    domain: "GEOMETRY",
    startPage: 97,
    endPage: 104,
  },
  {
    volume: 2,
    chapter: 9,
    chapterTitle: "Tam giác đồng dạng",
    lesson: 34,
    lessonTitle: "Ba trường hợp đồng dạng của hai tam giác",
    topicId: "tam-giac-dong-dang",
    domain: "GEOMETRY",
    startPage: 105,
    endPage: 114,
  },
  {
    volume: 2,
    chapter: 9,
    chapterTitle: "Tam giác đồng dạng",
    lesson: 35,
    lessonTitle: "Định lý Pythagore và ứng dụng",
    topicId: "tam-giac-dong-dang",
    domain: "GEOMETRY",
    startPage: 115,
    endPage: 122,
  },
  {
    volume: 2,
    chapter: 9,
    chapterTitle: "Tam giác đồng dạng",
    lesson: 36,
    lessonTitle: "Các trường hợp đồng dạng của hai tam giác vuông",
    topicId: "tam-giac-dong-dang",
    domain: "GEOMETRY",
    startPage: 123,
    endPage: 130,
  },
  {
    volume: 2,
    chapter: 10,
    chapterTitle: "Một số hình khối trong thực tiễn",
    lesson: 37,
    lessonTitle: "Hình chóp tam giác đều",
    topicId: "hinh-khoi-trong-thuc-tien",
    domain: "GEOMETRY",
    startPage: 131,
    endPage: 136,
  },
  {
    volume: 2,
    chapter: 10,
    chapterTitle: "Một số hình khối trong thực tiễn",
    lesson: 38,
    lessonTitle: "Hình chóp tứ giác đều",
    topicId: "hinh-khoi-trong-thuc-tien",
    domain: "GEOMETRY",
    startPage: 137,
    endPage: 142,
  },
];

export function findLessonMetadata(volume: 1 | 2, pageNumber: number): LessonMetadata {
  const match = TOAN8_KNTT_CURRICULUM.find(
    (l) => l.volume === volume && pageNumber >= l.startPage && pageNumber <= l.endPage
  );

  if (match) return match;

  if (volume === 1) {
    if (pageNumber < 5) {
      return {
        volume: 1,
        chapter: 1,
        chapterTitle: "Mở đầu",
        lesson: 0,
        lessonTitle: "Mục lục & Giới thiệu",
        topicId: "don-thuc-da-thuc",
        domain: "ALGEBRA",
        startPage: 1,
        endPage: 4,
      };
    }
    return TOAN8_KNTT_CURRICULUM[TOAN8_KNTT_CURRICULUM.length - 1];
  } else {
    if (pageNumber < 5) {
      return {
        volume: 2,
        chapter: 6,
        chapterTitle: "Mở đầu Tập 2",
        lesson: 0,
        lessonTitle: "Mục lục Tập 2",
        topicId: "phan-thuc-dai-so",
        domain: "ALGEBRA",
        startPage: 1,
        endPage: 4,
      };
    }
    return TOAN8_KNTT_CURRICULUM[TOAN8_KNTT_CURRICULUM.length - 1];
  }
}
